"""MaxEnt phonological grammar (UR → SR).

This module implements the phonological component of the joint model.
It scores the probability that an underlying representation (UR) is
realised as a particular surface form (SR).

Model
-----
The grammar is a log-linear (MaxEnt) model:
    P(SR | UR) ∝ exp(-H(UR, SR))
    H(UR, SR) = Σ_c  w_c · violations_c(UR, SR)

where w_c ≥ 0 are learned weights and violations_c counts how many
times constraint c fires on the UR→SR mapping.

Constraints
-----------
All constraints are *MAP(x, y) instances (see phonology/constraints.py).
One per ordered segment pair (x ≠ y).  Weights are initialised from
panphon featural distance (the P-map prior).

Partition function
------------------
Z(UR) = Σ_{SR'} exp(-H(UR, SR')) is approximated by summing over a
finite candidate set generated by candidates_for() (see DECISION POINT
note in phonology/candidates.py for the FST alternative).

Caches
------
_viol_cache : {(ur, sr) → np.ndarray}
    Violation vectors are weight-independent and cached permanently.
_cand_cache : {ur → set[str]}
    Candidate SR sets depend only on the UR and alphabet; cached permanently.
Both caches survive weight updates (no need to invalidate them).

Weight learning
---------------
Weights are updated via fit_weights() using L-BFGS-B (scipy).
The objective is negative log-posterior:
    -log P(w | data) = Σ H(ur, sr) + log Z(ur)   [neg log-likelihood]
                     + Σ w_c² / (2σ_c²)           [half-normal prior]
where σ_c = prior_weight of constraint c (from panphon distance).
The w ≥ 0 constraint is enforced via L-BFGS-B bounds.

Extensibility
-------------
run_weight_update() is the single call-site for weight updates.
Swap fit_weights for an HMC sampler to get full posterior over weights.
"""

from __future__ import annotations

import numpy as np
from scipy.optimize import minimize

from agme.phonology.candidates import candidates_for
from agme.phonology.constraints import StarMapConstraint
from agme.utils import levenshtein_alignment, logsumexp


class MaxEntPhonology:
    """Log-linear (MaxEnt) model over UR→SR mappings.

    Parameters
    ----------
    constraints : list[StarMapConstraint]
        The full constraint set.  Includes *MAP(a,b) substitution constraints
        plus *MAP(∅,b) insertion and *MAP(a,∅) deletion constraints (all
        represented as StarMapConstraint with x or y set to None).
    alphabet : list[str]
        The phoneme inventory.
    """

    def __init__(
        self,
        constraints: list[StarMapConstraint],
        alphabet: list[str],
        identity_only: bool = False,
        rng: np.random.Generator | None = None,
    ) -> None:
        self.constraints = constraints
        self.alphabet = alphabet
        # When True, P(SR|UR) = 1 if SR==UR else 0.  Used to test the
        # segmenter in isolation, without any phonological alternations.
        self.identity_only = identity_only
        # Seeded RNG passed from Model.fit() — used in candidates_for() so
        # that the random multi-edit candidate set is deterministic given seed.
        self._rng = rng
        # Weights in constraint order (w ≥ 0 enforced during learning)
        self.weights: np.ndarray = np.array(
            [c.prior_weight for c in constraints], dtype=np.float64
        )
        # Caches (weight-independent)
        self._viol_cache: dict[tuple[str, str], np.ndarray] = {}
        self._cand_cache: dict[str, set[str]] = {}
        # Harmony cache: {(ur, sr) → float}.  Valid between weight updates;
        # cleared by run_weight_update() since harmony = w · viol_vec changes
        # with weights.  Replaces np.dot per call with a dict lookup.
        self._harmony_cache: dict[tuple[str, str], float] = {}
        # Accumulated (ur, sr) pairs for the next weight update
        self._accumulated: list[tuple[str, str]] = []

        # ----------------------------------------------------------------
        # Pre-computed index arrays for vectorized violation counting.
        #
        # Segment symbol → integer index.  Index 0 is the null sentinel (∅).
        # Alphabet segments are indexed 1 … len(alphabet).
        # This allows alignment pair counts to be stored in a 2-D matrix
        # and all context-free constraint violations to be read out with a
        # single numpy fancy-index operation, replacing the Python listcomp.
        # ----------------------------------------------------------------
        self._seg_to_idx: dict[str | None, int] = {None: 0}
        for _i, _seg in enumerate(alphabet, start=1):
            self._seg_to_idx[_seg] = _i
        _n = len(alphabet) + 1   # matrix dimension (null + alphabet)
        self._n_syms: int = _n

        # Constraint x/y indices — shape (N_constraints,)
        self._c_x_idx: np.ndarray = np.array(
            [self._seg_to_idx.get(c.x, 0) for c in constraints], dtype=np.intp
        )
        self._c_y_idx: np.ndarray = np.array(
            [self._seg_to_idx.get(c.y, 0) for c in constraints], dtype=np.intp
        )
        # Boolean mask: True where the constraint is context-free (common case).
        self._c_context_free: np.ndarray = np.array(
            [c.left_ctx is None and c.right_ctx is None for c in constraints],
            dtype=bool,
        )

    # ------------------------------------------------------------------
    # Core scoring
    # ------------------------------------------------------------------

    def violation_vector(self, ur: str, sr: str) -> np.ndarray:
        """Cached violation vector for (ur, sr).

        On a cache miss:
          1. Compute levenshtein_alignment(ur, sr) once.
          2. Build a 2-D integer count matrix C where C[ur_idx, sr_idx] = number
             of times that alignment pair occurred.  Both None (∅) and alphabet
             segments are mapped to integers via self._seg_to_idx.
          3. Extract all context-free constraint violations with a single numpy
             fancy-index: viols = C[c_x_idx, c_y_idx]  — O(N_constraints) numpy.
          4. Context-sensitive constraints (rare; not produced by current builders)
             fall back to count_from_alignment.
        """
        key = (ur, sr)
        if key not in self._viol_cache:
            alignment = levenshtein_alignment(ur, sr)

            # Build count matrix in one Python pass over the alignment.
            count_matrix = np.zeros((self._n_syms, self._n_syms), dtype=np.float64)
            s2i = self._seg_to_idx
            for ur_seg, sr_seg in alignment:
                count_matrix[s2i.get(ur_seg, 0), s2i.get(sr_seg, 0)] += 1.0

            # Vectorized lookup for context-free constraints (all current ones).
            viols = count_matrix[self._c_x_idx, self._c_y_idx]

            # Context-sensitive constraints overwrite their slots (rare fallback).
            if not self._c_context_free.all():
                for idx in np.where(~self._c_context_free)[0]:
                    viols[idx] = self.constraints[idx].count_from_alignment(
                        alignment, sr
                    )

            self._viol_cache[key] = viols
        return self._viol_cache[key]

    def harmony(self, ur: str, sr: str) -> float:
        """H(ur, sr) = w · violations(ur, sr).  Higher = more marked.

        Results are cached between MaxEnt weight updates.  The cache is
        cleared by run_weight_update() since harmony values depend on weights.
        """
        key = (ur, sr)
        if key not in self._harmony_cache:
            self._harmony_cache[key] = float(
                np.dot(self.weights, self.violation_vector(ur, sr))
            )
        return self._harmony_cache[key]

    def _candidates(self, ur: str) -> set[str]:
        if ur not in self._cand_cache:
            # Pass the model's RNG so multi-edit candidates are reproducible.
            self._cand_cache[ur] = candidates_for(ur, self.alphabet, rng=self._rng)
        return self._cand_cache[ur]

    def log_prob(self, ur: str, sr: str) -> float:
        """log P(SR | UR) = -H(ur, sr) - log Z(ur).

        If identity_only=True, returns 0.0 when ur==sr and -inf otherwise,
        bypassing all constraint scoring.  Use this to test the segmenter
        independently of the phonological grammar.
        """
        if self.identity_only:
            return 0.0 if ur == sr else float("-inf")
        cands = self._candidates(ur)
        cands = cands | {sr}  # always include the observed SR
        log_z = logsumexp([-self.harmony(ur, c) for c in cands])
        return -self.harmony(ur, sr) - log_z

    # ------------------------------------------------------------------
    # Weight learning
    # ------------------------------------------------------------------

    def accumulate(self, ur: str, sr: str) -> None:
        """Record a (ur, sr) pair for the next weight update."""
        self._accumulated.append((ur, sr))

    def fit_weights(self, learning_rate: float = 1.0) -> None:
        """Update weights via L-BFGS-B on the accumulated (ur, sr) pairs.

        Minimises:  -log-likelihood  +  half-normal prior penalty
        Clears the accumulation buffer after the update.
        """
        if not self._accumulated:
            return

        pairs = list(self._accumulated)
        self._accumulated.clear()

        # Pre-compute violation vectors and candidate sets.
        # When the same UR appears with multiple SRs (e.g. in allomorphic pairs),
        # union all observed SRs into the candidate set for that UR so that
        # the partition function Z(ur) is computed over all attested outputs.
        all_cands: dict[str, set[str]] = {}
        obs_viols: list[np.ndarray] = []
        for ur, sr in pairs:
            base_cands = self._candidates(ur)
            all_cands[ur] = all_cands.get(ur, base_cands) | {sr}
            obs_viols.append(self.violation_vector(ur, sr))

        # Prior σ per constraint (from P-map initialisation)
        prior_sigma = np.array([c.prior_weight for c in self.constraints], dtype=np.float64)
        prior_sigma = np.where(prior_sigma > 0, prior_sigma, 1.0)

        def neg_log_posterior(w: np.ndarray) -> tuple[float, np.ndarray]:
            """Objective for L-BFGS-B: negative log-posterior and its gradient.

            Returns (scalar_loss, gradient_vector).
            L-BFGS-B minimises, so we return -log P(w | data).
            """
            total_nll = 0.0
            grad = np.zeros_like(w)
            for (ur, sr), obs_v in zip(pairs, obs_viols):
                cands = all_cands[ur]
                # Harmony H(ur, c) = w · violations(ur, c)  for each candidate c
                harm = {c: float(np.dot(w, self.violation_vector(ur, c))) for c in cands}
                # log Z(ur) = log Σ_c exp(-H(ur,c))
                log_z = logsumexp([-h for h in harm.values()])
                # neg log-likelihood for this pair: H(ur, sr) + log Z(ur)
                total_nll += harm[sr] + log_z
                # MaxEnt gradient: observed violations − expected violations
                # E[violations] = Σ_c P(c|ur,w) · violations(ur,c)
                exp_viols = np.zeros(len(self.constraints))
                for c, h in harm.items():
                    exp_viols += np.exp(-h - log_z) * self.violation_vector(ur, c)
                grad += obs_v - exp_viols  # positive = gradient of log-likelihood

            # Half-normal prior penalty: Σ w_i² / (2σ_i²)  (σ_i = P-map prior weight)
            prior_nll = float(np.sum(w**2 / (2 * prior_sigma**2)))
            prior_grad = w / prior_sigma**2

            # We minimise -log posterior; negate the log-likelihood gradient
            return total_nll + prior_nll, -grad + prior_grad

        result = minimize(
            neg_log_posterior,
            x0=self.weights.copy(),
            jac=True,
            method="L-BFGS-B",
            bounds=[(0.0, None)] * len(self.weights),
            options={"maxiter": 200, "ftol": 1e-9},
        )
        self.weights = result.x
        # Harmony values depend on weights: clear cache after each update.
        # Violation vectors are weight-independent and are NOT cleared.
        self._harmony_cache.clear()

    # ------------------------------------------------------------------
    # Extensibility hook: weight_updater swap-in point
    # ------------------------------------------------------------------

    def run_weight_update(self) -> None:
        """Call this to trigger a weight update step.

        Currently delegates to fit_weights (MAP via L-BFGS-B).
        Future extension: swap for HMC posterior sampling.
        No-op when identity_only=True.
        """
        if self.identity_only:
            self._accumulated.clear()
            return
        self.fit_weights()

    # ------------------------------------------------------------------
    # Introspection
    # ------------------------------------------------------------------

    def faithfulness_weights(self) -> dict[str, dict]:
        """Return a dict of constraint → {weight, prior, deviation}."""
        result = {}
        for c, w in zip(self.constraints, self.weights):
            result[repr(c)] = {
                "weight": float(w),
                "prior": c.prior_weight,
                "deviation": float(w) - c.prior_weight,
            }
        return result
