"""MaxEnt phonological grammar (UR → SR).

This module implements the phonological component of the joint model.
It scores the probability that an underlying representation (UR) is
realised as a particular surface form (SR).

Model
-----
The grammar is a log-linear (MaxEnt) model:
    P(SR | UR) ∝ exp(-H(UR, SR))
    H(UR, SR) = Σ_c  w_c · violations_c(UR, SR)

where w_c ≥ 0 are learned weights and violations_c counts how many
times constraint c fires on the UR→SR mapping.

Constraints
-----------
All constraints are *MAP(x, y) instances (see phonology/constraints.py).
One per ordered segment pair (x ≠ y).  Weights are initialised from
panphon featural distance (the P-map prior).

Partition function
------------------
Z(UR) = Σ_{SR'} exp(-H(UR, SR')) is approximated by summing over a
finite candidate set generated by candidates_for() (see DECISION POINT
note in phonology/candidates.py for the FST alternative).

Caches
------
_viol_cache : {(ur, sr) → np.ndarray}
    Violation vectors are weight-independent and cached permanently.
_cand_cache : {ur → set[str]}
    Candidate SR sets depend only on the UR and alphabet; cached permanently.
_viol_matrix_cache : {ur → np.ndarray}  shape (n_cands, n_constraints)
    Violation matrix for all candidates of a given UR.  Weight-independent;
    cached permanently.  Rows are appended when a new SR is first seen.
_cand_to_row : {ur → {sr → int}}
    Row index of each SR in the corresponding violation matrix.
_harmonies_cache : {ur → np.ndarray}  shape (n_cands,)
    H(ur, c) = V_ur @ w for every candidate c.  Recomputed lazily from the
    violation matrix and current weights; cleared after each weight update.
Both _viol_* caches survive weight updates; _harmonies_cache does not.

Levenshtein note
----------------
levenshtein_alignment() is only called inside violation_vector(), which is
itself cached by _viol_cache.  Every call to levenshtein_alignment therefore
corresponds to a genuinely new (ur, sr) pair — there is nothing further to
cache there.

Weight learning
---------------
Weights are updated via fit_weights() using L-BFGS-B (scipy).
The objective is negative log-posterior:
    -log P(w | data) = Σ H(ur, sr) + log Z(ur)   [neg log-likelihood]
                     + Σ w_c² / (2σ_c²)           [half-normal prior]
where σ_c = prior_weight of constraint c (from panphon distance).
The w ≥ 0 constraint is enforced via L-BFGS-B bounds.

Extensibility
-------------
run_weight_update() is the single call-site for weight updates.
Swap fit_weights for an HMC sampler to get full posterior over weights.
"""

from __future__ import annotations

from collections import Counter

import numpy as np
from scipy.optimize import minimize

from agme.phonology.candidates import candidates_for
from agme.phonology.constraints import StarMapConstraint
from agme.utils import levenshtein_alignment, logsumexp


class MaxEntPhonology:
    """Log-linear (MaxEnt) model over UR→SR mappings.

    Parameters
    ----------
    constraints : list[StarMapConstraint]
        The full constraint set.  Includes *MAP(a,b) substitution constraints
        plus *MAP(∅,b) insertion and *MAP(a,∅) deletion constraints (all
        represented as StarMapConstraint with x or y set to None).
    alphabet : list[str]
        The phoneme inventory.
    """

    def __init__(
        self,
        constraints: list[StarMapConstraint],
        alphabet: list[str],
        identity_only: bool = False,
        rng: np.random.Generator | None = None,
    ) -> None:
        self.constraints = constraints
        self.alphabet = alphabet
        # When True, P(SR|UR) = 1 if SR==UR else 0.  Used to test the
        # segmenter in isolation, without any phonological alternations.
        self.identity_only = identity_only
        # Seeded RNG passed from Model.fit() — used in candidates_for() so
        # that the random multi-edit candidate set is deterministic given seed.
        self._rng = rng
        # Weights in constraint order (w ≥ 0 enforced during learning)
        self.weights: np.ndarray = np.array(
            [c.prior_weight for c in constraints], dtype=np.float64
        )
        # Permanent caches (weight-independent) ---------------------------
        self._viol_cache: dict[tuple[str, str], np.ndarray] = {}
        self._cand_cache: dict[str, set[str]] = {}
        # Per-UR violation matrix: ur → ndarray of shape (n_cands, n_constraints).
        # Built on first access; rows are appended when a new SR is encountered.
        self._viol_matrix_cache: dict[str, np.ndarray] = {}
        # ur → {sr: row_index} — maps each candidate SR to its row in the matrix.
        self._cand_to_row: dict[str, dict[str, int]] = {}
        # Weight-dependent cache (cleared after each weight update) --------
        # ur → H(ur, *) = V_ur @ w, shape (n_cands,).  Avoids recomputing the
        # matmul on every log_prob call within the same sweep.
        self._harmonies_cache: dict[str, np.ndarray] = {}
        # Accumulated (ur, sr) observation counts for the next weight update.
        # Counter deduplicates: identical pairs across tokens/sweeps are stored
        # once and multiplied by count in the gradient, so memory is O(unique pairs)
        # rather than O(tokens × sweeps).
        self._accumulated: Counter[tuple[str, str]] = Counter()

        # ----------------------------------------------------------------
        # Pre-computed index arrays for vectorized violation counting.
        #
        # Segment symbol → integer index.  Index 0 is the null sentinel (∅).
        # Alphabet segments are indexed 1 … len(alphabet).
        # This allows alignment pair counts to be stored in a 2-D matrix
        # and all context-free constraint violations to be read out with a
        # single numpy fancy-index operation, replacing the Python listcomp.
        # ----------------------------------------------------------------
        self._seg_to_idx: dict[str | None, int] = {None: 0}
        for _i, _seg in enumerate(alphabet, start=1):
            self._seg_to_idx[_seg] = _i
        _n = len(alphabet) + 1   # matrix dimension (null + alphabet)
        self._n_syms: int = _n

        # Constraint x/y indices — shape (N_constraints,)
        self._c_x_idx: np.ndarray = np.array(
            [self._seg_to_idx.get(c.x, 0) for c in constraints], dtype=np.intp
        )
        self._c_y_idx: np.ndarray = np.array(
            [self._seg_to_idx.get(c.y, 0) for c in constraints], dtype=np.intp
        )
        # Boolean mask: True where the constraint is context-free (common case).
        self._c_context_free: np.ndarray = np.array(
            [c.left_ctx is None and c.right_ctx is None for c in constraints],
            dtype=bool,
        )

    # ------------------------------------------------------------------
    # Core scoring
    # ------------------------------------------------------------------

    def violation_vector(self, ur: str, sr: str) -> np.ndarray:
        """Cached violation vector for (ur, sr).

        On a cache miss:
          1. Compute levenshtein_alignment(ur, sr) once.
          2. Build a 2-D integer count matrix C where C[ur_idx, sr_idx] = number
             of times that alignment pair occurred.  Both None (∅) and alphabet
             segments are mapped to integers via self._seg_to_idx.
          3. Extract all context-free constraint violations with a single numpy
             fancy-index: viols = C[c_x_idx, c_y_idx]  — O(N_constraints) numpy.
          4. Context-sensitive constraints (rare; not produced by current builders)
             fall back to count_from_alignment.
        """
        key = (ur, sr)
        if key not in self._viol_cache:
            alignment = levenshtein_alignment(ur, sr)

            # Build count matrix in one Python pass over the alignment.
            count_matrix = np.zeros((self._n_syms, self._n_syms), dtype=np.float64)
            s2i = self._seg_to_idx
            for ur_seg, sr_seg in alignment:
                count_matrix[s2i.get(ur_seg, 0), s2i.get(sr_seg, 0)] += 1.0

            # Vectorized lookup for context-free constraints (all current ones).
            viols = count_matrix[self._c_x_idx, self._c_y_idx]

            # Context-sensitive constraints overwrite their slots (rare fallback).
            if not self._c_context_free.all():
                for idx in np.where(~self._c_context_free)[0]:
                    viols[idx] = self.constraints[idx].count_from_alignment(
                        alignment, sr
                    )

            self._viol_cache[key] = viols
        return self._viol_cache[key]

    def harmony(self, ur: str, sr: str) -> float:
        """H(ur, sr) = w · violations(ur, sr).  Higher = more marked.

        Kept for external introspection.  log_prob() and fit_weights() use
        the vectorized _harmonies_cache path instead of calling this directly.
        """
        return float(np.dot(self.weights, self.violation_vector(ur, sr)))

    def _candidates(self, ur: str) -> set[str]:
        if ur not in self._cand_cache:
            # Pass the model's RNG so multi-edit candidates are reproducible.
            self._cand_cache[ur] = candidates_for(ur, self.alphabet, rng=self._rng)
        return self._cand_cache[ur]

    def _ensure_cand_matrix(self, ur: str, sr: str) -> tuple[np.ndarray, int]:
        """Return (V_ur, sr_row_idx) for vectorized scoring.

        V_ur has shape (n_cands, n_constraints).  Built on first call for a
        given UR from its cached candidate set.  If sr is not already in the
        candidate set, a new row is appended (rare: only when an observed SR
        falls outside the random candidate sample).

        Weight-independent — safe to call during L-BFGS-B optimization.
        """
        if ur not in self._cand_to_row:
            cands = sorted(self._candidates(ur))
            self._cand_to_row[ur] = {c: i for i, c in enumerate(cands)}
            if cands:
                self._viol_matrix_cache[ur] = np.stack(
                    [self.violation_vector(ur, c) for c in cands]
                )
            else:
                self._viol_matrix_cache[ur] = np.empty(
                    (0, len(self.constraints)), dtype=np.float64
                )

        cand_to_row = self._cand_to_row[ur]
        if sr not in cand_to_row:
            # SR not in the sampled candidate set — append a row.
            # Also invalidate the harmonies cache for this UR since the matrix grew.
            idx = len(cand_to_row)
            cand_to_row[sr] = idx
            new_row = self.violation_vector(ur, sr)[np.newaxis, :]
            self._viol_matrix_cache[ur] = np.vstack(
                [self._viol_matrix_cache[ur], new_row]
            )
            self._harmonies_cache.pop(ur, None)

        return self._viol_matrix_cache[ur], self._cand_to_row[ur][sr]

    def log_prob(self, ur: str, sr: str) -> float:
        """log P(SR | UR) = -H(ur, sr) - log Z(ur).

        Vectorized: computes H for all candidates as V_ur @ w in one matmul,
        then caches the result per UR until the next weight update.

        If identity_only=True, returns 0.0 when ur==sr and -inf otherwise,
        bypassing all constraint scoring.
        """
        if self.identity_only:
            return 0.0 if ur == sr else float("-inf")

        V, sr_idx = self._ensure_cand_matrix(ur, sr)

        if ur not in self._harmonies_cache:
            self._harmonies_cache[ur] = V @ self.weights   # (n_cands,)
        harmonies = self._harmonies_cache[ur]

        # Numerically stable logsumexp over -harmonies
        neg_h = -harmonies
        m = neg_h.max()
        log_z = float(m + np.log(np.sum(np.exp(neg_h - m))))

        return float(-harmonies[sr_idx] - log_z)

    # ------------------------------------------------------------------
    # Weight learning
    # ------------------------------------------------------------------

    def accumulate(self, ur: str, sr: str) -> None:
        """Record a (ur, sr) observation for the next weight update."""
        self._accumulated[(ur, sr)] += 1

    def fit_weights(self, learning_rate: float = 1.0) -> None:
        """Update weights via L-BFGS-B on the accumulated (ur, sr) pairs.

        Minimises:  -log-likelihood  +  half-normal prior penalty
        Clears the accumulation buffer after the update.

        Vectorized: for each unique UR, harmonies = V_ur @ w and expected
        violations = softmax(-harmonies) @ V_ur are both single matmuls.
        """
        if not self._accumulated:
            return

        # pair_counts: {(ur, sr): count} — unique pairs only (memory-efficient)
        pair_counts: dict[tuple[str, str], int] = dict(self._accumulated)
        self._accumulated.clear()

        # Group observed counts by UR so each UR's violation matrix is
        # accessed once per L-BFGS-B iteration, not once per observation.
        ur_to_sr_counts: dict[str, dict[str, int]] = {}
        for (ur, sr), count in pair_counts.items():
            ur_to_sr_counts.setdefault(ur, {})[sr] = (
                ur_to_sr_counts.get(ur, {}).get(sr, 0) + count
            )

        # Ensure all violation matrices are built before the optimizer runs
        # (avoids side-effects inside the closure).
        for ur, sr_counts in ur_to_sr_counts.items():
            for sr in sr_counts:
                self._ensure_cand_matrix(ur, sr)

        # Snapshot of observed violation vectors (weight-independent).
        obs_viols: dict[tuple[str, str], np.ndarray] = {
            (ur, sr): self.violation_vector(ur, sr)
            for ur, sr_counts in ur_to_sr_counts.items()
            for sr in sr_counts
        }

        # Prior σ per constraint (from P-map initialisation)
        prior_sigma = np.array([c.prior_weight for c in self.constraints], dtype=np.float64)
        prior_sigma = np.where(prior_sigma > 0, prior_sigma, 1.0)

        def neg_log_posterior(w: np.ndarray) -> tuple[float, np.ndarray]:
            """Objective for L-BFGS-B: negative log-posterior and its gradient.

            Returns (scalar_loss, gradient_vector).
            L-BFGS-B minimises, so we return -log P(w | data).

            Vectorized inner loop:
              harmonies  = V_ur @ w                    one matmul per unique UR
              probs      = softmax(-harmonies)          one exp + normalise
              exp_viols  = probs @ V_ur                 one matmul per unique UR
            """
            total_nll = 0.0
            grad = np.zeros_like(w)

            for ur, sr_counts in ur_to_sr_counts.items():
                V = self._viol_matrix_cache[ur]       # (n_cands, n_constraints)
                cand_to_row = self._cand_to_row[ur]

                harmonies = V @ w                      # (n_cands,)
                neg_h = -harmonies
                m = neg_h.max()
                exp_neg_h = np.exp(neg_h - m)
                z = exp_neg_h.sum()
                log_z = float(m + np.log(z))
                probs = exp_neg_h / z                  # (n_cands,) — softmax

                # Expected violations: one matmul replaces a per-candidate loop
                exp_viols = probs @ V                  # (n_constraints,)

                for sr, count in sr_counts.items():
                    sr_idx = cand_to_row[sr]
                    total_nll += count * (harmonies[sr_idx] + log_z)
                    # Gradient: count × (observed − expected) violations
                    grad += count * (obs_viols[(ur, sr)] - exp_viols)

            # Half-normal prior penalty: Σ w_i² / (2σ_i²)  (σ_i = P-map prior weight)
            prior_nll = float(np.sum(w**2 / (2 * prior_sigma**2)))
            prior_grad = w / prior_sigma**2

            # We minimise -log posterior; negate the log-likelihood gradient
            return total_nll + prior_nll, -grad + prior_grad

        result = minimize(
            neg_log_posterior,
            x0=self.weights.copy(),
            jac=True,
            method="L-BFGS-B",
            bounds=[(0.0, None)] * len(self.weights),
            options={"maxiter": 200, "ftol": 1e-9},
        )
        self.weights = result.x
        # Harmonies depend on weights: clear cache after each update.
        # Violation matrices are weight-independent and are NOT cleared.
        self._harmonies_cache.clear()

    # ------------------------------------------------------------------
    # Extensibility hook: weight_updater swap-in point
    # ------------------------------------------------------------------

    def run_weight_update(self) -> None:
        """Call this to trigger a weight update step.

        Currently delegates to fit_weights (MAP via L-BFGS-B).
        Future extension: swap for HMC posterior sampling.
        No-op when identity_only=True.
        """
        if self.identity_only:
            self._accumulated.clear()
            return
        self.fit_weights()

    # ------------------------------------------------------------------
    # Introspection
    # ------------------------------------------------------------------

    def faithfulness_weights(self) -> dict[str, dict]:
        """Return a dict of constraint → {weight, prior, deviation}."""
        result = {}
        for c, w in zip(self.constraints, self.weights):
            result[repr(c)] = {
                "weight": float(w),
                "prior": c.prior_weight,
                "deviation": float(w) - c.prior_weight,
            }
        return result
